'use client';

import Link from 'next/link';
import { GitCompareArrows, Loader2, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useTenantData } from '@/lib/account/tenant-data-context';
import { useAccountBuildings } from '@/lib/account/use-account-buildings';

const AMENITIES = [
  ['Doorman', ['Doorman']], ['Gym', ['Gym']], ['In-Unit W/D', ['In-Unit W/D Available']], ['Elevator', ['Elevator']],
  ['Pets', ['Pets Allowed', 'Small Dogs Allowed', 'Large Dogs Allowed', 'Cats Allowed']], ['Pool', ['Pool', 'Indoor Pool', 'Outdoor Pool']], ['Private Outdoor Space', ['Outdoor Space']],
] as const;
const price = (value?: number) => value == null ? 'Not provided' : `From ${new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value)}`;

export default function ComparePage() {
  const { compareIds, toggleCompare, clearCompare } = useTenantData(); const { buildings, inventoryByBuilding, loading } = useAccountBuildings(compareIds);
  if (loading) return <div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin" /></div>;
  return <main className="mx-auto max-w-[1500px] px-4 py-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="font-serif text-3xl font-bold">Compare Buildings</h1><p className="text-sm text-muted-foreground">Compare up to 10 buildings. Missing verified data is shown as Not provided.</p></div>{compareIds.length > 0 && <Button variant="outline" onClick={() => void clearCompare()}>Clear all</Button>}</div>{buildings.length ? <div className="mt-6 overflow-x-auto rounded-2xl border bg-card"><table className="w-full min-w-[1180px] text-left text-sm"><thead className="bg-muted/70 text-xs uppercase text-muted-foreground"><tr><th className="px-3 py-3">Building</th><th className="px-3 py-3">Neighborhood</th><th className="px-3 py-3">Address</th>{['Studio', '1 Bed', '2 Beds', '3 Beds'].map((label) => <th key={label} className="px-3 py-3">{label}</th>)}{AMENITIES.map(([label]) => <th key={label} className="px-3 py-3">{label}</th>)}<th className="px-3 py-3">Availability</th><th className="px-3 py-3">Last Updated</th><th /></tr></thead><tbody>{buildings.map((building) => { const inventory = inventoryByBuilding[building.id]; const amenities = new Set(building.amenities ?? []); return <tr key={building.id} className="border-t align-top"><td className="px-3 py-4 font-semibold"><Link href={`/buildings/${building.slug}`} className="text-navy hover:text-primary-hover">{building.name}</Link></td><td className="px-3 py-4">{building.neighborhood ?? building.borough ?? 'Not provided'}</td><td className="max-w-60 px-3 py-4">{building.address || 'Not provided'}</td>{([0,1,2,3] as const).map((bedroom) => <td key={bedroom} className="whitespace-nowrap px-3 py-4 font-medium">{price(inventory?.bedroomMinimums[bedroom])}</td>)}{AMENITIES.map(([label, values]) => <td key={label} className="px-3 py-4">{values.some((value) => amenities.has(value)) ? 'Yes' : 'Not provided'}</td>)}<td className="px-3 py-4">{inventory ? `${inventory.availableCount} available` : 'Not provided'}</td><td className="whitespace-nowrap px-3 py-4">{inventory?.updatedAt ? new Date(inventory.updatedAt).toLocaleDateString() : building.updated_at ? new Date(building.updated_at).toLocaleDateString() : 'Not provided'}</td><td className="px-3 py-3"><Button size="icon" variant="ghost" aria-label={`Remove ${building.name}`} onClick={() => void toggleCompare(building.id, false)}><X className="h-4 w-4" /></Button></td></tr>; })}</tbody></table></div> : <div className="mt-10 rounded-2xl border bg-card p-8 text-center"><GitCompareArrows className="mx-auto h-9 w-9 text-muted-foreground" /><p className="mt-3 text-muted-foreground">Choose buildings to start a comparison.</p><Button asChild className="mt-4"><Link href="/">Browse Buildings</Link></Button></div>}</main>;
}
