'use client';

import {FormEvent,useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {Loader2} from 'lucide-react';
import {accountFetch} from '@/lib/account/client';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import type {Database} from '@/lib/database.types';
import {useAuth} from '@/lib/auth-context';
import {propertyEmailTemplate} from '@/lib/property-email-templates';

type Case=Database['public']['Tables']['rental_cases']['Row'];type Snapshot=Database['public']['Tables']['rental_case_recommendation_snapshots']['Row'];type History=Database['public']['Tables']['rental_case_status_history']['Row'];type Feedback=Database['public']['Tables']['rental_case_recommendation_feedback']['Row'];type Registration=Database['public']['Tables']['rental_case_property_registrations']['Row'];
type Outbox=Database['public']['Tables']['property_contact_outbox']['Row'];
type Tour=Database['public']['Tables']['rental_case_tours']['Row'];type Application=Database['public']['Tables']['applications']['Row'];
type ApplicationHistory=Database['public']['Tables']['application_status_history']['Row'];
type Payload={rentalCase:Case;inquiry:{move_in_date:string|null;monthly_budget:number|null;bedrooms:string|null;message:string|null;lease_term_months:number|null;contact_preference:string|null;contact_name:string|null}|null;building:{name:string;address:string;slug:string}|null;recommendations:Snapshot[];history:History[];feedback:Feedback[];registrations:Registration[];notifications:Array<{id:string;status:string;event_type:string}>;outbox:Outbox[];tours:Tour[];applications:Application[];applicationHistory:ApplicationHistory[]};
const labels:Record<string,{title:string;owner:string;next:string}>={submitted:{title:'Request received',owner:'NoFeeGo Admin',next:'Your request is being reviewed.'},reviewed:{title:'Ready for assignment',owner:'NoFeeGo Admin',next:'An active Agent will be assigned.'},agent_assigned:{title:'Agent assigned',owner:'Assigned Agent',next:'The Agent is preparing current options.'},options_sent:{title:'Options ready',owner:'You',next:'Review and select a specific option.'},interested:{title:'Option selected',owner:'Assigned Agent',next:'The Agent will register your selection with the Property.'},registered_with_property:{title:'Checking with property',owner:'Property team',next:'We are confirming current terms.'},property_acknowledged:{title:'Availability confirmed',owner:'Assigned Agent',next:'Review confirmed terms and tour details.'},tour_scheduled:{title:'Tour scheduled',owner:'You',next:'Attend or contact the Agent to reschedule.'},application_started:{title:'Application started',owner:'You',next:'Continue through the official Property application.'},application_submitted:{title:'Application submitted',owner:'Property team',next:'Await the Property decision.'},lease_signed:{title:'Lease confirmed',owner:'Complete',next:'Your Rental Case is complete.'},closed_lost:{title:'Case closed',owner:'Complete',next:'You can start a new request.'},cancelled:{title:'Request cancelled',owner:'Complete',next:'You can start a new request.'}};
const nextActions:Record<'tenant'|'agent'|'admin',Record<string,string[]>>={
 tenant:{submitted:['cancelled'],reviewed:['cancelled'],agent_assigned:['cancelled'],options_sent:['cancelled'],interested:['cancelled'],registered_with_property:['cancelled'],property_acknowledged:['cancelled'],tour_scheduled:['cancelled'],application_started:['cancelled'],application_submitted:['cancelled']},
 agent:{property_acknowledged:['tour_scheduled','closed_lost'],tour_scheduled:['application_started','closed_lost'],application_started:['application_submitted','closed_lost'],application_submitted:['lease_signed','closed_lost']},
 admin:{property_acknowledged:['tour_scheduled','closed_lost','cancelled'],tour_scheduled:['application_started','closed_lost','cancelled'],application_started:['application_submitted','closed_lost','cancelled'],application_submitted:['lease_signed','closed_lost','cancelled']}
};

export function RentalCaseWorkspace({caseId,audience}:{caseId:string;audience:'tenant'|'agent'|'admin'}){
 const {profile}=useAuth();
 const [payload,setPayload]=useState<Payload|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState<string|null>(null);
 const load=useCallback(()=>accountFetch<Payload>(`/api/account/rental-cases?caseId=${encodeURIComponent(caseId)}`).then(setPayload).catch(c=>setError(c instanceof Error?c.message:'CASE_LOAD_FAILED')),[caseId]);useEffect(()=>{load()},[load]);
 async function action(path:string,body:unknown){setBusy(true);setError(null);try{await accountFetch(path,{method:'POST',body:JSON.stringify(body)});setNotice('Saved. Everyone sees the same Case state.');await load()}catch(c){setError(c instanceof Error?c.message:'ACTION_FAILED')}finally{setBusy(false)}}
 async function assign(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await action(`/api/admin/cases/${caseId}/assign`,{agentId:f.get('agentId')})}
 async function register(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await action(`/api/agent/cases/${caseId}/registrations`,{organizationId:f.get('organizationId'),buildingId:payload!.rentalCase.building_id,recommendationId:payload!.rentalCase.selected_recommendation_id,propertyEmail:f.get('propertyEmail')})}
 async function grantAccess(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await action('/api/admin/building-access',{organizationId:f.get('organizationId'),buildingId:payload!.rentalCase.building_id})}
 async function createContact(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await action(`/api/cases/${caseId}/property-contact`,{action:'create_email',purpose:emailTemplate.purpose,subject:f.get('subject'),bodyText:f.get('bodyText'),idempotencyKey:crypto.randomUUID()})}
 async function outboxAction(outboxId:string,outboxAction:'approve'|'mark_sent'){await action(`/api/cases/${caseId}/property-contact`,{action:outboxAction,outboxId})}
 async function recordTour(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await action(`/api/agent/cases/${caseId}/progress`,{action:'tour',buildingId:payload!.rentalCase.building_id,unitId:payload!.recommendations.find(r=>r.id===payload!.rentalCase.selected_recommendation_id)?.unit_id??null,startsAt:new Date(String(f.get('startsAt'))).toISOString(),timeZone:'America/New_York',meetingLocation:f.get('meetingLocation')||null,contactName:f.get('contactName')||null,contactPhone:null,propertyStatus:f.get('propertyStatus'),tenantStatus:f.get('tenantStatus'),status:f.get('status'),meetingInstructions:f.get('instructions')||null,tenantFeedback:f.get('feedback')||null,internalNote:null})}
 async function updateApplication(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await action(`/api/agent/cases/${caseId}/progress`,{action:'application',status:f.get('status'),note:f.get('note')||null,leaseReference:f.get('leaseReference')||null})}
 if(error&&!payload)return <main className="mx-auto max-w-3xl p-6"><h1 className="text-2xl font-bold">Rental Case unavailable</h1><p role="alert" className="mt-3 text-destructive">{error}</p><Button asChild className="mt-4"><Link href={`/sign-in?next=${encodeURIComponent(window.location.pathname)}`}>Sign in and continue</Link></Button></main>;
 if(!payload)return <div className="flex min-h-[50vh] items-center justify-center" role="status"><Loader2 className="h-7 w-7 animate-spin"/><span className="sr-only">Loading Rental Case</span></div>;
 const state=labels[payload.rentalCase.status]??{title:payload.rentalCase.status,owner:'NoFeeGo',next:'Check back for an update.'};
 const emailTemplate=propertyEmailTemplate({caseId,caseStatus:payload.rentalCase.status,buildingName:payload.building?.name??'Rental Case',floorPlan:payload.rentalCase.selected_floor_plan??payload.rentalCase.preferred_unit_type??'Flexible',moveInDate:payload.inquiry?.move_in_date??null,budget:payload.inquiry?.monthly_budget??null,contactShareConsent:payload.rentalCase.contact_share_consent,tenantDisplayName:payload.inquiry?.contact_name??null});
 const allowed=nextActions[audience][payload.rentalCase.status]??[];
 return <main className="mx-auto max-w-4xl p-4 sm:p-6"><p className="text-sm uppercase tracking-wide text-muted-foreground">{audience} workspace</p><h1 className="mt-1 text-3xl font-bold">{payload.building?.name??'Rental Case'}</h1><p className="text-sm text-muted-foreground">{payload.building?.address}</p><section className="mt-5 grid gap-3 rounded-xl border bg-white p-5 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Current status</p><p className="font-semibold">{state.title}</p></div><div><p className="text-xs text-muted-foreground">Next owner</p><p className="font-semibold">{state.owner}</p></div><div><p className="text-xs text-muted-foreground">What happens next</p><p className="text-sm">{state.next}</p></div></section><section className="mt-4 grid gap-3 rounded-xl border p-4 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Move-in</p><p>{payload.inquiry?.move_in_date??'Flexible'}</p></div><div><p className="text-xs text-muted-foreground">Budget</p><p>{payload.inquiry?.monthly_budget?`$${payload.inquiry.monthly_budget.toLocaleString()}`:'Not supplied'}</p></div><div><p className="text-xs text-muted-foreground">Bedrooms</p><p>{payload.inquiry?.bedrooms??payload.rentalCase.preferred_unit_type??'Flexible'}</p></div></section>{payload.notifications.some(n=>n.status==='manual_required')&&audience==='admin'&&<p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Manual notification required: {payload.notifications.filter(n=>n.status==='manual_required').length} handoff(s) are waiting for secure delivery.</p>}{notice&&<p role="status" className="mt-4 rounded-lg bg-success/15 p-3 text-sm">{notice}</p>}{error&&<p role="alert" className="mt-4 rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
 <section className="mt-6"><h2 className="text-xl font-bold">Recommendations</h2>{payload.recommendations.length?<ul className="mt-3 space-y-3">{payload.recommendations.map(item=><li key={item.id} className={`rounded-xl border p-4 ${payload.rentalCase.selected_recommendation_id===item.id?'border-primary bg-primary/5':''}`}><strong>{item.unit_label||'Unit option'}</strong><p className="text-sm">Gross ${item.gross_rent??'—'} · Net effective ${item.net_effective_rent??'—'} · {item.lease_term_months??'—'} months</p><p className="text-sm">Available {item.available_date??'confirming'}{item.concession?` · ${item.concession}`:''}</p><p className="text-xs text-muted-foreground">Source checked {item.source_freshness?new Date(item.source_freshness).toLocaleString():'not supplied'}</p>{audience==='tenant'&&['options_sent','interested'].includes(payload.rentalCase.status)&&<div className="mt-3 flex gap-2"><Button disabled={busy} onClick={()=>action(`/api/cases/${caseId}/recommendation-feedback`,{recommendationId:item.id,decision:'interested'})}>Select this option</Button><Button disabled={busy} variant="outline" onClick={()=>action(`/api/cases/${caseId}/recommendation-feedback`,{recommendationId:item.id,decision:'not_interested'})}>Not interested</Button></div>}</li>)}</ul>:<p className="mt-2 text-muted-foreground">No recommendations have been sent yet.</p>}</section>
 {audience==='agent'&&['agent_assigned','options_sent'].includes(payload.rentalCase.status)&&<section className="mt-6 rounded-xl border p-4"><h2 className="text-xl font-bold">Recommend verified inventory</h2><p className="mt-1 text-sm text-muted-foreground">Choose a current authorized Unit or Floor Plan. Rent, concession, availability, lease term, and verification time are copied server-side into an immutable snapshot.</p><Button asChild className="mt-3"><Link href={`/agent?case=${caseId}`}>Choose from authorized inventory</Link></Button></section>}
 {audience==='admin'&&payload.rentalCase.status==='submitted'&&<Button disabled={busy} className="mt-6" onClick={()=>action(`/api/cases/${caseId}/transition`,{status:'reviewed'})}>Mark reviewed</Button>}{audience==='admin'&&payload.rentalCase.status==='reviewed'&&<form onSubmit={assign} className="mt-6 flex gap-2 rounded-xl border p-4"><Input name="agentId" placeholder="Active Agent profile UUID" required/><Button disabled={busy}>Assign Agent</Button></form>}
 {audience==='agent'&&payload.rentalCase.building_id&&<div className="mt-6 rounded-xl border p-4"><h2 className="text-xl font-bold">Property Outreach</h2><p className="mt-1 text-sm text-muted-foreground">Request current availability through the reviewed Leasing Team contact. This does not register or identify the Tenant.</p><Button asChild className="mt-3"><Link href={`/agent/property-outreach?case=${caseId}`}>Contact leasing team</Link></Button></div>}
 {audience==='agent'&&payload.rentalCase.status==='interested'&&<form onSubmit={register} className="mt-6 grid gap-3 rounded-xl border p-4"><h2 className="text-xl font-bold">Register selected option with Property</h2><Input name="organizationId" placeholder="Authorized Property organization UUID" required/><Input name="propertyEmail" type="email" placeholder="Property contact email" required/><Button disabled={busy}>Register and send invitation</Button><p className="text-xs text-muted-foreground">Formal customer registration remains separate from general availability outreach.</p><p className="text-xs text-muted-foreground">If automatic email delivery is unavailable, the Registration remains saved and Admin receives a manual delivery fallback.</p></form>}
 {(audience==='agent'||audience==='admin')&&payload.rentalCase.building_id&&<section className="mt-6 rounded-xl border p-4"><h2 className="text-xl font-bold">Property Contact Outbox</h2><p className="mt-1 text-sm text-muted-foreground">The Portal selects the current reviewed Leasing Team contact and prepares an editable draft. You send it from your own verified business email; the website never impersonates you or sends it automatically.</p>{payload.outbox.length===0?<form onSubmit={createContact} className="mt-4 grid gap-3"><Input name="subject" defaultValue={emailTemplate.subject} required/><textarea name="bodyText" required rows={7} className="rounded-md border p-3 text-sm" defaultValue={emailTemplate.body}/><Button disabled={busy}>Create editable draft</Button></form>:<ul className="mt-4 space-y-3">{payload.outbox.map(item=>{const mailto=`mailto:${encodeURIComponent(item.recipient_email)}?subject=${encodeURIComponent(item.subject)}&body=${encodeURIComponent(item.body_text)}`;return <li key={item.id} className="rounded-lg bg-muted/50 p-4"><p className="text-xs text-muted-foreground">From</p><p className="text-sm">{profile?.business_email_verified_at?profile.business_email:'Add or verify your business email before continuing'}</p><p className="mt-2 text-xs text-muted-foreground">To</p><p className="text-sm">{item.recipient_email}</p><p className="mt-3 font-semibold">{item.subject}</p><pre className="mt-2 whitespace-pre-wrap rounded-md bg-white p-3 text-sm">{item.body_text}</pre><p className="mt-2 text-xs text-muted-foreground">Case {caseId} · {payload.building?.name} · status {payload.rentalCase.status.replaceAll('_',' ')}</p><div className="mt-3 flex flex-wrap gap-2">{item.status==='draft'&&<Button disabled={busy} onClick={()=>outboxAction(item.id,'approve')}>Approve draft</Button>}<Button variant="outline" onClick={()=>navigator.clipboard.writeText(item.subject)}>Copy subject</Button><Button variant="outline" onClick={()=>navigator.clipboard.writeText(item.body_text)}>Copy body</Button>{profile?.business_email_verified_at&&profile.business_email&&<Button asChild><a href={mailto}>Open in my email</a></Button>}{['draft','approved','manual_required'].includes(item.status)&&<Button disabled={busy||!profile?.business_email_verified_at} onClick={()=>outboxAction(item.id,'mark_sent')}>Mark as sent</Button>}</div>{item.manual_sent_at&&<p className="mt-2 text-xs text-muted-foreground">Marked sent {new Date(item.manual_sent_at).toLocaleString()}</p>}</li>})}</ul>}</section>}
 {audience==='admin'&&<form onSubmit={grantAccess} className="mt-6 flex flex-wrap gap-2 rounded-xl border p-4"><h2 className="w-full text-lg font-bold">Property Building access</h2><Input name="organizationId" className="min-w-64 flex-1" placeholder="Property organization UUID" required/><Button disabled={busy}>Grant this Building</Button></form>}
 {audience==='agent'&&payload.rentalCase.building_id&&['property_acknowledged','tour_scheduled'].includes(payload.rentalCase.status)&&<section className="mt-6 rounded-xl border p-4"><h2 className="text-xl font-bold">Tour progress</h2>{payload.tours.map(t=><p key={t.id} className="mt-2 text-sm">{new Date(t.starts_at).toLocaleString()} · {t.status.replaceAll('_',' ')} · Property {t.property_status.replaceAll('_',' ')} · Tenant {t.tenant_status.replaceAll('_',' ')}</p>)}<form onSubmit={recordTour} className="mt-4 grid gap-3 sm:grid-cols-2"><Input name="startsAt" type="datetime-local" required/><Input name="meetingLocation" placeholder="Meeting location"/><Input name="contactName" placeholder="Leasing contact"/><select name="status" className="h-10 rounded-md border bg-background px-3"><option value="proposed">Proposed</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="reschedule_requested">Reschedule requested</option><option value="cancelled">Cancelled</option></select><select name="propertyStatus" className="h-10 rounded-md border bg-background px-3"><option value="proposed">Property proposed</option><option value="confirmed">Property confirmed</option><option value="declined">Property declined</option><option value="reschedule_requested">Property needs reschedule</option></select><select name="tenantStatus" className="h-10 rounded-md border bg-background px-3"><option value="proposed">Tenant proposed</option><option value="confirmed">Tenant confirmed</option><option value="declined">Tenant declined</option><option value="reschedule_requested">Tenant needs reschedule</option></select><Input name="instructions" placeholder="Meeting instructions"/><Input name="feedback" placeholder="Tenant feedback after tour"/><Button disabled={busy} className="sm:col-span-2">Save tour record</Button></form></section>}
 {(audience==='agent'||audience==='admin')&&['tour_scheduled','application_started','application_submitted','additional_documents_requested','approved','lease_sent'].includes(payload.rentalCase.status)&&<section className="mt-6 rounded-xl border p-4"><h2 className="text-xl font-bold">Application progress</h2>{payload.applications.map(a=><p key={a.id} className="mt-2 text-sm">{a.status.replaceAll('_',' ')}{a.next_follow_up_at?` · Next follow-up ${new Date(a.next_follow_up_at).toLocaleString()}`:''}</p>)}<form onSubmit={updateApplication} className="mt-4 grid gap-3 sm:grid-cols-2"><select name="status" className="h-10 rounded-md border bg-background px-3"><option value="started">Application started</option><option value="submitted">Application submitted</option><option value="additional_information_requested">Additional documents requested</option><option value="under_review">Under review</option><option value="approved">Approved</option><option value="lease_sent">Lease sent</option><option value="lease_signed">Lease signed</option><option value="declined">Declined</option><option value="withdrawn">Withdrawn</option></select><Input name="note" placeholder="Permitted status note"/><Input name="leaseReference" placeholder="Non-sensitive lease reference (lease signed only)"/><Button disabled={busy} className="sm:col-span-2">Apply protected transition</Button></form></section>}
 {allowed.length>0&&<section className="mt-6"><h2 className="text-lg font-bold">Case actions</h2><div className="mt-2 flex flex-wrap gap-2">{allowed.map(status=><Button key={status} variant="outline" disabled={busy} onClick={()=>action(`/api/cases/${caseId}/transition`,{status,reason:['closed_lost','cancelled'].includes(status)?'Recorded by authorized user':null})}>{labels[status]?.title??status}</Button>)}</div></section>}
 {audience==='tenant'&&<section className="mt-6 rounded-xl border p-4"><h2 className="text-xl font-bold">Application progress</h2>{payload.applications.length?<div className="mt-3 space-y-2">{payload.applications.map(item=><div key={item.id}><p className="font-semibold">{item.status.replaceAll('_',' ')}</p>{item.missing_document_categories?.length>0&&<p className="text-sm text-amber-800">Missing: {item.missing_document_categories.join(', ')}</p>}{item.next_follow_up_at&&<p className="text-sm text-muted-foreground">Next follow-up {new Date(item.next_follow_up_at).toLocaleString()}</p>}</div>)}</div>:<p className="mt-2 text-sm text-muted-foreground">No active Application yet. Select a Recommendation to continue.</p>}<ol className="mt-4 space-y-2">{payload.applicationHistory.map(item=><li key={item.id} className="border-l-2 pl-3 text-sm">{item.new_status.replaceAll('_',' ')} · {new Date(item.created_at).toLocaleString()}</li>)}</ol></section>}
 <section className="mt-6"><h2 className="text-xl font-bold">Case history</h2><ol className="mt-3 space-y-2">{payload.history.map(item=><li key={item.id} className="border-l-2 pl-3 text-sm">{labels[item.to_status]?.title??item.to_status} · {new Date(item.created_at).toLocaleString()}</li>)}</ol></section></main>
}
