'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Bot, CheckCircle2, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { accountFetch } from '@/lib/account/client';
import { useAuth } from '@/lib/auth-context';
import type { RentalDemandContext } from '@/components/rental-demand-form';
import { roommateDraftSchema, type RoommateDraftInput } from '@/lib/roommate/schemas';

const stages = ['Home', 'Lifestyle', 'Readiness', 'Profile'] as const;
type Draft = Partial<RoommateDraftInput>;
const defaults: Draft = { flexibilityDaysBefore:0, flexibilityDaysAfter:0, leaseTerm:'12_months', roommatesNeeded:1,
  smokingStatus:'never', petStatus:'no_pets', petAllergies:'None', workPattern:'hybrid', sleepSchedule:'Standard daytime', noisePreference:'moderate',
  cleaningHabits:'regularly_clean', guestFrequency:'occasionally', temperaturePreference:'moderate', qualificationStatus:'figuring_out', creditCategory:null,
  guarantorStatus:'not_sure', identityVerificationWillingness:'maybe_later', matchNotifications:true, marketingConsent:false };

export function RoommateInterestForm({ context }: { context: RentalDemandContext }) {
  const { user } = useAuth(); const [stage,setStage]=useState(0); const [preview,setPreview]=useState(false); const [draft,setDraft]=useState<Draft>(()=>{let saved:Draft={};if(typeof window!=='undefined'){try{saved=JSON.parse(localStorage.getItem(`nofeego:roommate-mvp:${context.buildingId}:${context.floorPlan}`)??'{}')}catch{}}return {...defaults,...saved,buildingId:context.buildingId,buildingName:context.buildingName||'Selected home',buildingSlug:context.buildingSlug||'buildings',unitId:context.unitId||null,floorPlan:context.floorPlan||'Any available floor plan',bedroomCount:null};});
  const [text,setText]=useState(''); const [pending,setPending]=useState<Record<string,unknown>|null>(null); const [busy,setBusy]=useState(false);
  const [error,setError]=useState(''); const [result,setResult]=useState<{id:string;hasPotentialMatches:boolean}|null>(null);
  const key=useMemo(()=>`nofeego:roommate-mvp:${context.buildingId}:${context.floorPlan}`,[context.buildingId,context.floorPlan]);
  const set=(name:keyof Draft,value:unknown)=>setDraft(v=>({...v,[name]:value} as Draft));
  useEffect(()=>{if(user?.email&&!draft.contactEmail)queueMicrotask(()=>setDraft(v=>({...v,contactEmail:user.email??''})))},[user?.email,draft.contactEmail]);
  useEffect(()=>{localStorage.setItem(key,JSON.stringify(draft))},[draft,key]);
  async function extract(field:'move_in_timing'|'lifestyle'|'bio') { setBusy(true);setError('');try{const r=await accountFetch<{data:Record<string,unknown>}>('/api/account/roommate-extract',{method:'POST',body:JSON.stringify({field,text,current:draft})});setPending(r.data)}catch{setError('I could not interpret that. Please use the choices or enter the fields directly.')}finally{setBusy(false)}}
  function confirm(){if(pending)setDraft(v=>({...v,...pending}));setPending(null);setText('')}
  async function submit(){if(!user){location.assign(`/sign-in?next=${encodeURIComponent(location.pathname+location.search)}`);return}const parsed=roommateDraftSchema.safeParse(draft);if(!parsed.success){setError(parsed.error.issues[0]?.message??'Review your answers.');return}setBusy(true);try{const r=await accountFetch<{id:string;hasPotentialMatches:boolean}>('/api/account/roommate-interests',{method:'POST',body:JSON.stringify(parsed.data)});localStorage.removeItem(key);setResult(r)}catch{setError('Unable to join the interest list. Please try again.')}finally{setBusy(false)}}
  if(result)return <Success result={result} context={context}/>;
  return <main className="mx-auto min-h-[calc(100dvh-5rem)] max-w-4xl px-4 py-6 sm:px-6"><Button asChild variant="ghost" className="px-0"><Link href={`/buildings/${context.buildingSlug}`}><ArrowLeft className="mr-2 h-4 w-4"/>Back to home</Link></Button>
    <div className="mt-3 overflow-hidden rounded-2xl border bg-white shadow-sm"><header className="border-b p-5 sm:p-7"><div className="flex items-center gap-3"><span className="rounded-full bg-primary/10 p-2"><Bot className="h-5 w-5 text-primary"/></span><div><h1 className="font-serif text-2xl font-bold text-navy">Find a roommate</h1><p className="text-sm text-muted-foreground">Share this home</p></div></div><div className="mt-5 grid grid-cols-4 gap-2">{stages.map((s,i)=><button key={s} onClick={()=>{setStage(i);setPreview(false)}} className={`border-b-2 pb-2 text-xs font-semibold sm:text-sm ${i===stage&&!preview?'border-primary text-primary':i<stage||preview?'border-navy text-navy':'border-muted text-muted-foreground'}`}>{s}</button>)}</div></header>
    <section className="max-h-[calc(100dvh-15rem)] overflow-y-auto p-5 sm:p-7"><div className="rounded-2xl bg-muted/60 p-4 text-sm"><p className="font-semibold">{context.buildingName||'Selected home'} — {context.floorPlan||'Any available floor plan'}</p><p className="mt-1 text-muted-foreground">This home stays selected throughout the conversation.</p></div>
      {preview?<Preview draft={draft} edit={i=>{setStage(i);setPreview(false)}}/>:<>{stage===0&&<Home draft={draft} set={set} text={text} setText={setText} extract={()=>extract('move_in_timing')}/>} {stage===1&&<Lifestyle draft={draft} set={set} text={text} setText={setText} extract={()=>extract('lifestyle')}/>} {stage===2&&<Readiness draft={draft} set={set}/>} {stage===3&&<Profile draft={draft} set={set} text={text} setText={setText} extract={()=>extract('bio')} email={user?.email}/>}</>}
      {pending&&<div className="mt-5 rounded-xl border border-primary/30 bg-primary/5 p-4"><p className="font-semibold">Here&apos;s what I understood:</p><pre className="mt-2 whitespace-pre-wrap text-xs">{JSON.stringify(pending,null,2)}</pre><div className="mt-3 flex gap-2"><Button onClick={confirm}>Looks right</Button><Button variant="outline" onClick={()=>setPending(null)}>Edit</Button></div></div>}
      {error&&<p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}
      <div className="mt-7 flex justify-between"><Button variant="outline" disabled={stage===0&&!preview} onClick={()=>preview?setPreview(false):setStage(Math.max(0,stage-1))}>Back</Button>{preview?<Button disabled={busy} onClick={submit}>{busy&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Join the roommate interest list</Button>:<Button onClick={()=>stage===3?setPreview(true):setStage(stage+1)}>{stage===3?'Review profile':'Continue'}</Button>}</div>
    </section></div></main>;
}

function Home({draft,set,text,setText,extract}:SectionProps){return <Conversation title="Let’s confirm timing and budget." prompt={`You’re looking to share ${draft.buildingName} — ${draft.floorPlan}. Is that correct?`}><div className="flex flex-wrap gap-2"><Button variant={draft.homeConfirmed?'default':'outline'} onClick={()=>set('homeConfirmed',true)}>Yes</Button><Button asChild variant="outline"><Link href={`/buildings/${draft.buildingSlug}`}>Change floor plan</Link></Button></div><p className="text-sm font-medium">When would you like to move? You can answer naturally.</p><div className="flex gap-2"><Input value={text} onChange={e=>setText(e.target.value)} placeholder="Around September 1, a week earlier works"/><Button variant="outline" onClick={extract}>Interpret</Button></div><Grid><Field label="Move-in date"><Input type="date" value={String(draft.moveInDate??'')} onChange={e=>set('moveInDate',e.target.value)}/></Field><Field label="Maximum monthly budget per person"><Input type="number" min="1" value={String(draft.personalMonthlyBudget??'')} onChange={e=>set('personalMonthlyBudget',Number(e.target.value))}/></Field><Choice label="Lease term" value={draft.leaseTerm} set={v=>set('leaseTerm',v)} options={['12_months','18_plus_months','short_term','not_sure']}/><Field label="How many more roommates?"><Input type="number" min="1" max="7" value={Number(draft.roommatesNeeded??1)} onChange={e=>set('roommatesNeeded',Number(e.target.value))}/></Field></Grid><p className="text-xs text-muted-foreground">Home and timing complete · About 2 minutes remaining</p></Conversation>}
function Lifestyle({draft,set,text,setText,extract}:SectionProps){return <Conversation title="What makes a home work well for you?" prompt="Describe your routine in one sentence, or use the choices below."><div className="flex gap-2"><Input value={text} onChange={e=>setText(e.target.value)} placeholder="I work from home, prefer quiet, and keep things tidy"/><Button variant="outline" onClick={extract}>Interpret</Button></div><Grid><Choice label="Smoking / vaping" value={draft.smokingStatus} set={v=>set('smokingStatus',v)} options={['never','outside_only','occasionally','prefer_not_to_say']}/><Choice label="Pets" value={draft.petStatus} set={v=>set('petStatus',v)} options={['no_pets','cat','dog','open_to_pets','allergies']}/><Choice label="Work pattern" value={draft.workPattern} set={v=>set('workPattern',v)} options={['on_site','hybrid','work_from_home','variable']}/><Choice label="Noise" value={draft.noisePreference} set={v=>set('noisePreference',v)} options={['quiet','moderate','social','flexible']}/><Choice label="Cleaning" value={draft.cleaningHabits} set={v=>set('cleaningHabits',v)} options={['very_tidy','regularly_clean','relaxed','discuss']}/><Choice label="Guests" value={draft.guestFrequency} set={v=>set('guestFrequency',v)} options={['rarely','occasionally','frequently','discuss']}/><Choice label="Temperature" value={draft.temperaturePreference} set={v=>set('temperaturePreference',v)} options={['cooler','moderate','warmer','flexible']}/><Field label="Sleep schedule"><Input value={String(draft.sleepSchedule??'')} onChange={e=>set('sleepSchedule',e.target.value)}/></Field></Grid></Conversation>}
function Readiness({draft,set}:BaseProps){return <Conversation title="Rental readiness" prompt="Financial details stay private. Potential roommates see only broad readiness labels."><Grid><Choice label="Qualification status" value={draft.qualificationStatus} set={v=>set('qualificationStatus',v)} options={['ready','preparing_documents','need_guarantor','figuring_out']}/><Choice label="Credit category (optional)" value={draft.creditCategory??'skip'} set={v=>set('creditCategory',v==='skip'?null:v)} options={['excellent','good','fair','skip']}/><Choice label="Income / guarantor readiness" value={draft.guarantorStatus} set={v=>set('guarantorStatus',v)} options={['independent','personal_guarantor','guarantor_service','not_sure']}/><Choice label="Identity verification" value={draft.identityVerificationWillingness} set={v=>set('identityVerificationWillingness',v)} options={['yes','maybe_later','no']}/></Grid></Conversation>}
function Profile({draft,set,text,setText,extract,email}:SectionProps&{email?:string}){return <Conversation title="Create your anonymous profile" prompt="Tell me about your routine and the home environment you enjoy. Don’t include contact details."><div className="flex gap-2"><Input value={text} onChange={e=>setText(e.target.value)} placeholder="I’m tidy, easygoing, and enjoy a quiet home"/><Button variant="outline" onClick={extract}>Help me write it</Button></div><Grid><Field label="Display name"><Input value={String(draft.displayName??'')} onChange={e=>set('displayName',e.target.value)}/></Field><Field label="Account email"><Input value={String(draft.contactEmail??email??'')} onChange={e=>set('contactEmail',e.target.value)}/></Field></Grid><Field label="Anonymous introduction"><textarea className="mt-1 min-h-24 w-full rounded-md border p-3 text-sm" maxLength={300} value={String(draft.bio??'')} onChange={e=>set('bio',e.target.value)}/></Field><Checks draft={draft} set={set}/></Conversation>}

type BaseProps={draft:Draft;set:(n:keyof Draft,v:unknown)=>void};
type SectionProps=BaseProps&{text:string;setText:(v:string)=>void;extract:()=>void};
function Conversation({title,prompt,children}:{title:string;prompt:string;children:React.ReactNode}){return <div className="mt-6"><div className="max-w-2xl rounded-2xl rounded-tl-sm bg-navy p-4 text-white"><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-white/80">{prompt}</p></div><div className="mt-5 space-y-4">{children}</div></div>}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-4 sm:grid-cols-2">{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-sm font-medium">{label}{children}</label>}
function Choice({label,value,set,options}:{label:string;value:unknown;set:(v:string)=>void;options:string[]}){return <Field label={label}><select className="mt-1 h-10 w-full rounded-md border bg-white px-3 text-sm" value={String(value??'')} onChange={e=>set(e.target.value)}>{options.map(o=><option key={o} value={o}>{o.replaceAll('_',' ')}</option>)}</select></Field>}
function Checks({draft,set}:BaseProps){return <div className="space-y-3 text-sm"><label className="flex gap-2"><input type="checkbox" checked={draft.termsAccepted===true} onChange={e=>set('termsAccepted',e.target.checked?true:undefined)}/><span>I agree to the Terms, Privacy Policy, Community Guidelines, and reporting process. Required.</span></label><label className="flex gap-2"><input type="checkbox" checked={draft.matchNotifications===true} onChange={e=>set('matchNotifications',e.target.checked)}/><span>Notify me about compatible roommate interest.</span></label><label className="flex gap-2"><input type="checkbox" checked={draft.marketingConsent===true} onChange={e=>set('marketingConsent',e.target.checked)}/><span>Send optional marketing email or SMS. Not required.</span></label></div>}
function Preview({draft,edit}:{draft:Draft;edit:(i:number)=>void}){const rows=[['Selected home',`${draft.buildingName} — ${draft.floorPlan}`,0],['Move-in timing',`${draft.moveInDate||'Missing'} · ${draft.leaseTerm||'Missing'} · ${draft.personalMonthlyBudget||'Missing'} per person`,0],['Lifestyle',`${draft.workPattern}, ${draft.noisePreference}, ${draft.cleaningHabits}`,1],['Rental readiness',`${draft.qualificationStatus}, ${draft.guarantorStatus}`,2],['Anonymous profile',draft.bio||'Missing',3]] as const;return <div className="mt-6"><h2 className="font-serif text-2xl font-bold">Review your profile</h2><p className="mt-1 text-sm text-muted-foreground">Nothing is submitted until you confirm.</p><div className="mt-5 divide-y rounded-xl border">{rows.map(([a,b,i])=><div key={a} className="flex items-start justify-between gap-4 p-4"><div><p className="font-semibold">{a}</p><p className="mt-1 text-sm text-muted-foreground">{b}</p></div><Button variant="ghost" size="sm" onClick={()=>edit(i)}>Edit</Button></div>)}</div></div>}
function Success({result}:{result:{id:string;hasPotentialMatches:boolean};context:RentalDemandContext}){const [busy,setBusy]=useState(false);async function ask(){setBusy(true);try{await accountFetch(`/api/account/roommate-interests/${result.id}/lead`,{method:'POST'});location.assign('/dashboard/requests')}finally{setBusy(false)}}return <main className="mx-auto max-w-3xl px-4 py-10"><div className="rounded-2xl border bg-white p-7 shadow-sm"><CheckCircle2 className="h-12 w-12 text-success"/><h1 className="mt-4 font-serif text-3xl font-bold">{result.hasPotentialMatches?'You’ve joined the roommate interest list for this home.':'You’re on the interest list for this home.'}</h1><p className="mt-2 text-muted-foreground">{result.hasPotentialMatches?'A potential match may be available.':'We’ll notify you when a compatible roommate joins.'}</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{result.hasPotentialMatches&&<Button asChild variant="outline"><Link href="/dashboard/roommates">View potential matches</Link></Button>}<Button asChild variant="outline"><Link href="/buildings">Add another home</Link></Button><Button disabled={busy} onClick={ask}>Ask about this home</Button></div><p className="mt-5 text-sm text-muted-foreground">Keep browsing—there is no need to wait for a match.</p></div></main>}
