'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Loader2 } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { useAuth } from '@/lib/auth-context';
import { supabase } from '@/lib/supabase/client';

type Item={id:string;building_id:string;floor_plan:string;personal_monthly_budget:number|null;move_in_date:string|null;lease_term:string|null;qualification_status:string|null;status:'active'|'paused'|'withdrawn'|'home_unavailable';submitted_at:string|null;contacted_at:string|null;linked_inquiry_id:string|null};
export default function AdminRoommateInterestsPage(){const {profile,loading}=useAuth();const router=useRouter();const [items,setItems]=useState<Item[]>([]);const [q,setQ]=useState('');const [status,setStatus]=useState('all');const [busy,setBusy]=useState(true);
  const load=useCallback(async()=>{setBusy(true);let query=supabase.from('roommate_interests').select('id,building_id,floor_plan,personal_monthly_budget,move_in_date,lease_term,qualification_status,status,submitted_at,contacted_at,linked_inquiry_id').order('submitted_at',{ascending:false});if(status!=='all')query=query.eq('status',status as Item['status']);const {data}=await query;setItems((data??[]) as Item[]);setBusy(false)},[status]);
  useEffect(()=>{if(!loading&&profile&&!profile.is_admin)router.replace('/');if(profile?.is_admin)queueMicrotask(()=>void load())},[loading,profile,router,load]);
  const filtered=useMemo(()=>items.filter(i=>`${i.building_id} ${i.floor_plan}`.toLowerCase().includes(q.toLowerCase())),[items,q]);
  async function mark(id:string,next:'active'|'paused'|'withdrawn'){await supabase.from('roommate_interests').update(next==='active'?{status:next,contacted_at:new Date().toISOString()}:{status:next}).eq('id',id);await load()}
  if(loading||!profile?.is_admin)return <main className="p-8"><Loader2 className="animate-spin"/></main>;
  return <main className="mx-auto max-w-7xl p-6"><h1 className="font-serif text-3xl font-bold">Roommate interests</h1><p className="mt-1 text-sm text-muted-foreground">Operational view; private contact and detailed lifestyle data are omitted.</p><div className="mt-5 flex gap-3"><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search building ID or floor plan"/><select className="rounded-md border px-3" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="paused">Paused</option><option value="withdrawn">Withdrawn</option></select></div>{busy?<Loader2 className="mt-8 animate-spin"/>:<div className="mt-5 overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-muted"><tr>{['Building','Floor plan','Budget','Move-in','Lease','Readiness','Status','Submitted','Lead','Actions'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map(i=><tr className="border-t" key={i.id}><td className="p-3 font-mono text-xs">{i.building_id}</td><td className="p-3">{i.floor_plan}</td><td className="p-3">{i.personal_monthly_budget??'—'}</td><td className="p-3">{i.move_in_date??'—'}</td><td className="p-3">{i.lease_term??'—'}</td><td className="p-3">{i.qualification_status??'—'}</td><td className="p-3">{i.status}</td><td className="p-3">{i.submitted_at?new Date(i.submitted_at).toLocaleDateString():'—'}</td><td className="p-3">{i.linked_inquiry_id?'Linked':'—'}</td><td className="p-3"><div className="flex gap-1"><Button size="sm" variant="outline" onClick={()=>mark(i.id,'active')}>Contacted</Button><Button size="sm" variant="outline" onClick={()=>mark(i.id,'paused')}>Pause</Button><Button size="sm" variant="ghost" onClick={()=>mark(i.id,'withdrawn')}>Close</Button></div></td></tr>)}</tbody></table></div>}</main>}
