'use client';

import { use, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Clipboard, ExternalLink, Loader2, Mail, Phone, ShieldCheck } from 'lucide-react';
import { accountFetch } from '@/lib/account/client';
import { Button } from '@/components/ui/button';
import { type AgentInventoryPayload, dateTime, inventoryFreshness, latestSnapshots, money } from '@/lib/agent-inventory';

type SortKey='available_date'|'gross_asc'|'gross_desc'|'net_asc'|'net_desc';

export default function AgentInventoryDetailPage({params}:{params:Promise<{buildingId:string}>}){
  const {buildingId}=use(params);
  const [data,setData]=useState<AgentInventoryPayload|null>(null),[error,setError]=useState('');
  const [floorPlan,setFloorPlan]=useState('all'),[bedrooms,setBedrooms]=useState('all'),[sort,setSort]=useState<SortKey>('available_date');
  const [availableNow,setAvailableNow]=useState(false),[concessionsOnly,setConcessionsOnly]=useState(false);
  useEffect(()=>{accountFetch<AgentInventoryPayload>(`/api/agent/inventory?building=${encodeURIComponent(buildingId)}`).then(setData).catch((reason:Error)=>setError(reason.message.includes('FORBIDDEN')?'You do not have permission to view this inventory.':'Inventory could not be loaded. Please try again.'))},[buildingId]);
  const detail=useMemo(()=>{if(!data?.buildings[0])return null;const building=data.buildings[0],units=data.units.filter(item=>item.building_id===building.id),snapshots=latestSnapshots(data.snapshots),sourceById=new Map(data.sources.map(source=>[source.id,source])),organization=data.organizations.find(item=>item.building_id===building.id),contacts=data.contacts.filter(item=>item.building_id===building.id&&item.is_active&&!item.needs_review),preferred=contacts[0],application=data.applications.find(item=>item.building_id===building.id);return {building,units,snapshots,sourceById,organization,contacts,preferred,application,fees:data.fees.filter(item=>item.building_id===building.id)}} ,[data]);
  const rows=useMemo(()=>{if(!detail)return[];const today=new Date().toISOString().slice(0,10);return detail.snapshots.map(snapshot=>({snapshot,unit:detail.units.find(unit=>unit.id===snapshot.unit_id),source:snapshot.source_id?detail.sourceById.get(snapshot.source_id):undefined,freshness:inventoryFreshness(snapshot)})).filter(row=>floorPlan==='all'||row.unit?.floorplan_name===floorPlan).filter(row=>bedrooms==='all'||String(row.unit?.bedrooms)===bedrooms).filter(row=>!availableNow||(row.snapshot.inventory_status==='available'&&(!row.snapshot.available_date||row.snapshot.available_date<=today))).filter(row=>!concessionsOnly||Boolean(row.snapshot.concession_text)).sort((a,b)=>sort==='available_date'?(a.snapshot.available_date??'9999').localeCompare(b.snapshot.available_date??'9999'):sort==='gross_asc'?(a.snapshot.rent??Infinity)-(b.snapshot.rent??Infinity):sort==='gross_desc'?(b.snapshot.rent??-Infinity)-(a.snapshot.rent??-Infinity):sort==='net_asc'?(a.snapshot.net_effective_rent??Infinity)-(b.snapshot.net_effective_rent??Infinity):(b.snapshot.net_effective_rent??-Infinity)-(a.snapshot.net_effective_rent??-Infinity));},[availableNow,bedrooms,concessionsOnly,detail,floorPlan,sort]);
  if(!data&&!error)return <div className="flex min-h-[55vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin"/><span className="ml-3">Loading authorized inventory…</span></div>;
  if(error&&!detail)return <main className="mx-auto max-w-3xl p-6"><p className="rounded-xl border p-6 text-center">{error}</p></main>;
  if(!detail)return null;
  const {building,organization,preferred,application}=detail;
  const latest=[...detail.snapshots].sort((a,b)=>b.captured_at.localeCompare(a.captured_at))[0];
  const freshness=inventoryFreshness(latest);
  const floorPlans=[...new Set(detail.units.flatMap(unit=>unit.floorplan_name?[unit.floorplan_name]:[]))].sort();
  const bedroomValues=[...new Set(detail.units.flatMap(unit=>unit.bedrooms==null?[]:[unit.bedrooms]))].sort((a,b)=>a-b);
  return <main className="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8">
    <Button asChild variant="ghost"><Link href="/agent"><ArrowLeft className="mr-2 h-4 w-4"/>Back to Agent Home</Link></Button>
    <header className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.16em] text-emerald-800"><ShieldCheck className="h-4 w-4"/>Authorized Agent Inventory</p><h1 className="mt-1 font-serif text-3xl font-bold">{building.name}</h1><p className="mt-1 text-muted-foreground">{building.address}, {building.city}, {building.state} {building.zip_code}</p><p className="text-sm text-muted-foreground">{building.neighborhood||building.borough||'Neighborhood not provided'}</p></div><FreshnessBadge value={freshness}/></header>
    {freshness==='Stale'&&<p role="alert" className="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm font-medium text-amber-950">This inventory is stale and must not be treated as real-time availability. Contact property to confirm.</p>}
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><Section title="Building & source"><Details rows={[["Building website",building.official_building_website],["Management company",building.management_company],["Inventory updated",dateTime(latest?.captured_at)],["Last verified",dateTime(latest?.source_id?detail.sourceById.get(latest.source_id)?.last_verified_at:building.last_verified_date)],["Data freshness",freshness],["Source status",latest?.source_id?detail.sourceById.get(latest.source_id)?.verification_status:null]]}/><div className="mt-4 flex flex-wrap gap-2">{building.official_building_website&&<ActionLink href={building.official_building_website} label="Visit property website"/>}{organization?.leasing_office_website&&<ActionLink href={organization.leasing_office_website} label="Visit leasing office"/>}{application?.application_url&&<ActionLink href={application.application_url} label="Open application website"/>}</div></Section>
      <Section title="Reviewed property contact"><Details rows={[["Property / management",organization?.name||building.management_company],["Leasing team",preferred?.name],["Contact role",preferred?.role_title||preferred?.purpose],["Leasing email",preferred?.email],["Leasing phone",preferred?.phone],["Office hours",preferred?.preferred_hours||organization?.office_hours],["Preferred method",preferred?.preferred_method],["Contact last verified",dateTime(preferred?.last_verified_at)]]}/>{preferred?<div className="mt-4 flex flex-wrap gap-2">{preferred.website&&<ActionLink href={preferred.website} label="Property website"/>}{preferred.email&&<><Button size="sm" variant="outline" asChild><a href={`mailto:${preferred.email}`}><Mail className="mr-2 h-4 w-4"/>Email leasing</a></Button><CopyButton value={preferred.email} label="Copy email"/></>}{preferred.phone&&<><Button size="sm" variant="outline" asChild><a href={`tel:${preferred.phone}`}><Phone className="mr-2 h-4 w-4"/>Call leasing</a></Button><CopyButton value={preferred.phone} label="Copy phone"/></>}</div>:<p className="mt-4 rounded-lg border border-dashed p-3 text-sm text-muted-foreground">Contact unavailable — no reviewed email or phone is available. No contact details have been inferred.</p>}</Section></div>
    <Section title="Authorized floor plans & units" className="mt-6"><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-5"><Filter label="Floor plan" value={floorPlan} onChange={setFloorPlan} options={[["all","All floor plans"],...floorPlans.map(value=>[value,value] as [string,string])]}/><Filter label="Bedrooms" value={bedrooms} onChange={setBedrooms} options={[["all","All bedrooms"],...bedroomValues.map(value=>[String(value),value===0?'Studio':`${value} bedroom`] as [string,string])]}/><Filter label="Sort" value={sort} onChange={value=>setSort(value as SortKey)} options={[["available_date","Available date"],["gross_asc","Gross rent ↑"],["gross_desc","Gross rent ↓"],["net_asc","Net effective ↑"],["net_desc","Net effective ↓"]]}/><Toggle label="Available now" checked={availableNow} onChange={setAvailableNow}/><Toggle label="Has concession" checked={concessionsOnly} onChange={setConcessionsOnly}/></div>
      {detail.snapshots.length===0?<p className="mt-5 rounded-xl border border-dashed p-5 text-sm text-muted-foreground">No authorized inventory. Public building information remains available.</p>:rows.length===0?<p className="mt-5 rounded-xl border border-dashed p-5 text-sm text-muted-foreground">No authorized units match these filters.</p>:<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1180px] text-left text-sm"><thead><tr className="border-b bg-muted/40">{['Floor plan / unit','Beds / baths','Gross rent','Net effective','Available','Lease term','Concession','Deposit / fees','Status','Verified'].map(label=><th key={label} className="px-3 py-3 font-semibold">{label}</th>)}</tr></thead><tbody>{rows.map(({snapshot,unit,source,freshness:rowFreshness})=>{const fees=detail.fees.filter(fee=>fee.unit_id===unit?.id);return <tr key={snapshot.id} className="border-b align-top"><td className="px-3 py-3"><strong>{unit?.floorplan_name||unit?.unit_type||'Floor plan'}</strong><br/><span className="text-muted-foreground">{unit?.unit_number?`Unit ${unit.unit_number}`:'Unit not provided'}</span></td><td className="px-3 py-3">{unit?.bedrooms??'—'} / {unit?.bathrooms??'—'}</td><td className="px-3 py-3">{money(snapshot.rent)}</td><td className="px-3 py-3">{money(snapshot.net_effective_rent)}</td><td className="px-3 py-3">{snapshot.available_date||'Not provided'}<br/><span className="text-xs text-muted-foreground">{snapshot.inventory_status==='available'?'Available':'Not current'}</span></td><td className="px-3 py-3">{unit?.lease_term?`${unit.lease_term} months`:'Not provided'}</td><td className="px-3 py-3">{snapshot.concession_text||'None confirmed'}</td><td className="px-3 py-3">{fees.length?fees.map(fee=>`${fee.fee_type}: ${money(fee.amount)}`).join(' · '):unit?.broker_fee?`Broker fee: ${money(unit.broker_fee)}`:'None confirmed'}</td><td className="px-3 py-3"><FreshnessBadge value={rowFreshness}/>{rowFreshness==='Stale'&&<p className="mt-1 text-xs text-amber-800">Contact property to confirm</p>}</td><td className="px-3 py-3">{dateTime(source?.last_verified_at||snapshot.captured_at)}</td></tr>})}</tbody></table></div>}
    </Section>
  </main>;
}

function Section({title,className='',children}:{title:string;className?:string;children:React.ReactNode}){return <section className={`rounded-2xl border bg-card p-5 shadow-sm ${className}`}><h2 className="font-serif text-xl font-bold">{title}</h2><div className="mt-4">{children}</div></section>}
function Details({rows}:{rows:[string,string|null|undefined][]}){return <dl className="grid gap-x-5 gap-y-3 sm:grid-cols-2">{rows.map(([label,value])=><div key={label}><dt className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 break-words text-sm">{value||'Not provided'}</dd></div>)}</dl>}
function ActionLink({href,label}:{href:string;label:string}){return <Button size="sm" variant="outline" asChild><a href={href} target="_blank" rel="noreferrer">{label}<ExternalLink className="ml-2 h-4 w-4"/></a></Button>}
function CopyButton({value,label}:{value:string;label:string}){return <Button size="sm" variant="outline" onClick={()=>navigator.clipboard.writeText(value)}><Clipboard className="mr-2 h-4 w-4"/>{label}</Button>}
function FreshnessBadge({value}:{value:'Current'|'Aging'|'Stale'}){const style=value==='Current'?'bg-emerald-100 text-emerald-900':value==='Aging'?'bg-amber-100 text-amber-900':'bg-slate-200 text-slate-800';return <span className={`inline-flex rounded-full px-3 py-1 text-xs font-semibold ${style}`}>{value}</span>}
function Filter({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:[string,string][]}){return <label className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}<select className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm font-normal normal-case tracking-normal text-foreground" value={value} onChange={event=>onChange(event.target.value)}>{options.map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="flex h-10 items-center gap-2 self-end rounded-md border px-3 text-sm"><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/>{label}</label>}
