'use client';

import { use, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Clipboard, ExternalLink, Loader2, Mail, Phone } from 'lucide-react';
import { accountFetch } from '@/lib/account/client';
import { Button } from '@/components/ui/button';
import { AgentInventoryPayload, dateTime, inventoryFreshness, latestSnapshots, money } from '@/lib/agent-inventory';

export default function AgentInventoryDetailPage({params}:{params:Promise<{buildingId:string}>}){
  const {buildingId}=use(params);
  const [data,setData]=useState<AgentInventoryPayload|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState('');
  useEffect(()=>{accountFetch<AgentInventoryPayload>(`/api/agent/inventory?building=${encodeURIComponent(buildingId)}`).then(setData).catch((reason:Error)=>setError(reason.message.includes('FORBIDDEN')?'You do not have permission to view this inventory.':'Inventory could not be loaded. Please try again.'))},[buildingId]);
  const detail=useMemo(()=>{if(!data?.buildings[0])return null;const building=data.buildings[0],units=data.units.filter(item=>item.building_id===building.id),snapshots=latestSnapshots(data.snapshots),source=data.sources[0],organizationId=data.propertyAccess.find(item=>item.building_id===building.id)?.organization_id,organization=data.organizations.find(item=>item.id===organizationId),contacts=data.contacts.filter(item=>item.building_id===building.id&&item.is_active),preferred=[...contacts].sort((a,b)=>Number(a.needs_review)-Number(b.needs_review)||Number(Boolean(b.last_successful_contact_at))-Number(Boolean(a.last_successful_contact_at)))[0],outbox=data.outbox[0],cases=data.cases.filter(item=>item.building_id===building.id),replyPending=Boolean(outbox&&['approved','queued','sent','simulated_sent'].includes(outbox.status));return {building,units,snapshots,source,organization,contacts,preferred,outbox,cases,replyPending,registrations:data.registrations.filter(item=>item.building_id===building.id)}} ,[data]);
  async function recommend(snapshotId:string,caseId:string){if(!detail)return;const snapshot=detail.snapshots.find(item=>item.id===snapshotId),unit=detail.units.find(item=>item.id===snapshot?.unit_id);if(!snapshot)return;setBusy(snapshotId);setError('');try{await accountFetch(`/api/agent/cases/${caseId}/recommendations`,{method:'POST',body:JSON.stringify({buildingId,unitId:snapshot.unit_id,unitLabel:unit?.unit_number??unit?.floorplan_name,grossRent:snapshot.rent,netEffectiveRent:snapshot.net_effective_rent,availableDate:snapshot.available_date,leaseTermMonths:unit?.lease_term,concession:snapshot.concession_text,sourceFreshness:snapshot.captured_at})})}catch{setError('Recommendation was rejected. Confirm the Case and inventory relationship.')}finally{setBusy('')}}
  if(!data&&!error)return <div className="flex min-h-[55vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin"/><span className="ml-3">Loading authorized inventory…</span></div>;
  if(error&&!detail)return <main className="mx-auto max-w-3xl p-6"><p className="rounded-xl border p-6 text-center">{error}</p></main>;
  if(!detail)return null;
  const {building}=detail;
  const feedback=data?.feedback??[];
  return <main className="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8"><Button asChild variant="ghost"><Link href="/agent/inventory"><ArrowLeft className="mr-2 h-4 w-4"/>Back to Inventory</Link></Button><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">Agent Inventory · Property Detail</p><h1 className="mt-1 font-serif text-3xl font-bold">{building.name}</h1><p className="mt-1 text-muted-foreground">{building.address}, {building.city}, {building.state} {building.zip_code}</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-900">{inventoryFreshness(detail.snapshots[0],detail.replyPending)}</span></div>{error&&<p role="alert" className="mt-4 rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><Section title="Building"><Details rows={[["Neighborhood",building.neighborhood],["Borough",building.borough],["Property type",building.building_type],["Pet policy",building.pet_friendly==null?null:building.pet_friendly?'Pet friendly':'Restrictions may apply'],["Amenities",building.amenities?.join(', ')],["Building notes",building.description],["Inventory source",detail.source?.source_name||detail.source?.source_type],["Last verified",detail.snapshots[0]?.captured_at?dateTime(detail.snapshots[0].captured_at):dateTime(detail.source?.last_verified_at)]]}/>{building.official_building_website&&<Button className="mt-4" variant="outline" asChild><a href={building.official_building_website} target="_blank" rel="noreferrer">Official website<ExternalLink className="ml-2 h-4 w-4"/></a></Button>}</Section>
      <Section title="Leasing Team / Property"><Details rows={[["Property Organization",detail.organization?.name],["Management company",building.management_company],["Preferred contact",detail.preferred?.name],["Role / purpose",detail.preferred?.role_title||detail.preferred?.purpose],["Preferred method",detail.preferred?.preferred_method],["Contact source",detail.preferred?.source_note],["Verification status",detail.preferred?detail.preferred.needs_review?'Needs review':'Reviewed':null],["Last successful contact",dateTime(detail.preferred?.last_successful_contact_at)],["Last contacted",dateTime(detail.preferred?.last_contacted_at)],["Current outreach",detail.outbox?.status.replaceAll('_',' ')]]}/>{detail.preferred?<div className="mt-4 flex flex-wrap gap-2">{detail.preferred.email&&<><Button size="sm" variant="outline" asChild><a href={`mailto:${detail.preferred.email}`}><Mail className="mr-2 h-4 w-4"/>Email</a></Button><Button size="sm" variant="outline" onClick={()=>navigator.clipboard.writeText(detail.preferred!.email!)}><Clipboard className="mr-2 h-4 w-4"/>Copy email</Button></>}{detail.preferred.phone&&<><Button size="sm" variant="outline" asChild><a href={`tel:${detail.preferred.phone}`}><Phone className="mr-2 h-4 w-4"/>Call</a></Button><Button size="sm" variant="outline" onClick={()=>navigator.clipboard.writeText(detail.preferred!.phone!)}><Clipboard className="mr-2 h-4 w-4"/>Copy phone</Button></>}</div>:<p className="mt-4 text-sm text-muted-foreground">No reviewed Leasing Team contact is available.</p>}<p className="mt-4 text-xs text-muted-foreground">Preferred contact is chosen from active, reviewed contacts with successful-contact history. {detail.contacts.length>1?`${detail.contacts.length-1} other active contact(s) remain available and unchanged.`:''}</p></Section>
    </div>
    <Section id="availability" title="Current Availability" className="mt-6">{detail.snapshots.length===0?<div><p>This building does not have current availability data.</p><Button className="mt-4" asChild><Link href={`/agent/property-outreach?case=${detail.cases[0]?.id??''}`}>Request latest availability</Link></Button></div>:<div className="grid gap-4 lg:grid-cols-2">{detail.snapshots.map(snapshot=>{const unit=detail.units.find(item=>item.id===snapshot.unit_id),source=detail.source?.id===snapshot.source_id?detail.source:null;return <article key={snapshot.id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{unit?.unit_number||unit?.floorplan_name||'Building-level summary'}</h3><span className="text-xs font-semibold">{inventoryFreshness(snapshot,detail.replyPending)}</span></div><Details rows={[["Floor plan",unit?.floorplan_name||unit?.unit_type],["Bedrooms / bathrooms",`${unit?.bedrooms??'—'} / ${unit?.bathrooms??'—'}`],["Gross rent",money(snapshot.rent)],["Net effective rent",money(snapshot.net_effective_rent)],["Available date",snapshot.available_date],["Lease term",unit?.lease_term?`${unit.lease_term} months`:null],["Concessions",snapshot.concession_text],["Unit status",snapshot.inventory_status],["Last verified",dateTime(snapshot.captured_at)],["Data source",source?.source_name||source?.source_type]]}/><select aria-label={`Add ${unit?.unit_number||'unit'} to Rental Case`} className="mt-4 h-10 w-full rounded-md border bg-background px-3 text-sm" defaultValue="" disabled={busy===snapshot.id} onChange={event=>{if(event.target.value)void recommend(snapshot.id,event.target.value)}}><option value="">Add to rental case / Recommend…</option>{detail.cases.map(item=><option key={item.id} value={item.id}>Case {item.id.slice(0,8)} · {item.status.replaceAll('_',' ')}</option>)}</select></article>})}</div>}</Section>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><Section title="Application and Leasing Policies"><Details rows={[["Application fee",null],["Income requirement",null],["Guarantor policy",null],["International student policy",null],["Deposit requirement",null],["Broker / client registration",null],["Commission / OP policy",null],["Tour policy",null],["Lease term policy",detail.units.some(item=>item.lease_term)?[...new Set(detail.units.map(item=>item.lease_term).filter(Boolean))].map(value=>`${value} months`).join(', '):null]]}/><p className="mt-3 text-xs text-muted-foreground">Fields not present in the deployed canonical Preview schema are shown as Not provided; no values are inferred.</p></Section><Section title="Related Activity"><Details rows={[["Interested tenants",String(detail.cases.filter(item=>feedback.some(value=>value.rental_case_id===item.id&&value.decision==='interested')).length)],["Related Rental Cases",String(detail.cases.length)],["Last outreach",dateTime(detail.outbox?.updated_at)],["Waiting for reply",detail.replyPending?'Yes':'No'],["Recent property response",dateTime(detail.outbox?.reply_received_at)],["Inventory updates",String(detail.snapshots.length)],["Current registration",detail.registrations[0]?.status]]}/><Button className="mt-4" asChild><Link href={`/agent/property-outreach?case=${detail.cases[0]?.id??''}`}>Open Property Outreach</Link></Button></Section></div>
  </main>;
}

function Section({title,id,className='',children}:{title:string;id?:string;className?:string;children:React.ReactNode}){return <section id={id} className={`rounded-2xl border bg-card p-5 shadow-sm ${className}`}><h2 className="font-serif text-xl font-bold">{title}</h2><div className="mt-4">{children}</div></section>}
function Details({rows}:{rows:[string,string|null|undefined][]}){return <dl className="grid gap-x-5 gap-y-3 sm:grid-cols-2">{rows.map(([label,value])=><div key={label}><dt className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 text-sm">{value||'Not provided'}</dd></div>)}</dl>}
